site_name: Darwinia Document
copyright: Copyright &copy; 2018 - 2024 Darwinia Network
theme:
  name: material
  logo: assets/darwinia.png
  favicon: assets/background.png
  font:
      text: Open Sans
      code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - header.autohide
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom

extra:
  homepage: https://darwinia.network
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darwinia-network
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/DarwiniaNetwork
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jbRk7znn4Q
    - icon: fontawesome/brands/telegram
      link: https://t.me/DarwiniaNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/darwinianetwork

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  # code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # lists 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # math
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: 'index.md'
  - Msgport:
    - Overview: 'msgport/overview.md'
    - Glossary: 'msgport/glossary.md'
    - Msgport Interfaces: 'msgport/interfaces.md'
    - Msgport Workflow: 'msgport/workflow.md'
    - Msgport API: 'msgport/api.md'
    - Msgport Scan: 'msgport/scan.md'
    - Messaging Protocols:
        - ORMP: 'msgport/messaging-protocols/ormp.md'
        - XCMP: 'msgport/messaging-protocols/xcmp.md'
        - LCMP(Deprecated): 'msgport/messaging-protocols/lcmp.md'
    - Supported Network: 'msgport/networks.md'
    - User Cases:
        - Token/Asset Bridge: 'msgport/user-cases/token-bridge.md'
        - Cross Chain Abstract Account: 'msgport/user-cases/abstract-account.md'
        - Multi Chains DAO Governance: 'msgport/user-cases/multichain-dao-governance.md'
    - Tutorial:
        - Pangolin > Sepolia Remix Demo: 'msgport/tutorial/remix-demo.md'
        - Pangolin > Sepolia Script Demo: 'msgport/tutorial/script-demo.md'
    - FAQ: 'msgport/faq.md'
    - TroubleSome: 'msgport/troublesome.md'
  - EVM+: 
    - Overview: 'evm/overview.md'
    - Chains And Explorers:
          - Darwinia Chain: 'evm/chains/darwinia.md'
          - Crab Chain: 'evm/chains/crab.md'
          - Pangolin Chain: 'evm/chains/pangolin.md'
          - Rollup Testnet: 'evm/chains/rollup.md'
    - Available Wallets: 'evm/wallets.md'
  - RING: 'ring.md'
  - Ecosystem And Developer Incentive Program: 'ecosystem.md'