site_name: Darwinia Docs
copyright: Copyright &copy; Darwinia Network
repo_url: https://github.com/darwinia-network/docs
repo_name: darwinia-network/docs
edit_uri: https://github.com/darwinia-network/docs/edit/main/docs
theme:
  name: material
  logo: resource/pics/darwinia-logo.png
  favicon: resource/pics/background.png
  font:
    text: San Francisco
    code: SFMono-Regular
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  generator: false
  homepage: https://darwinia.network
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darwinia-network
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/DarwiniaNetwork
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jbRk7znn4Q
    - icon: fontawesome/brands/telegram
      link: https://t.me/DarwiniaNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/darwinianetwork

extra_css:
  - resource/stylesheets/extra.css

extra_javascript:
  - resource/script/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true

nav:
  - Home: "index.md"
  - Learn Darwinia:
      - Chains:
          - Overview: "learn/chains/overview.md"
          - Darwinia Chain: "learn/chains/darwinia.md"
          - Crab Chain: "learn/chains/crab.md"
          - Pangolin Chain: "learn/chains/pangolin.md"
          - Rollup Testnet: "learn/chains/rollup.md"
      - Wallets: "learn/wallets.md"
      - Governance: "learn/governance.md"
      - Ethereum Compatibility:
          - Account System: "learn/ethereum-compatibility/account-system.md"
          - JSON-RPC APIs: "learn/ethereum-compatibility/jsonrpc.md"
          - Gas Compatibility: "learn/ethereum-compatibility/gas.md"
          - EVM Tracing: "learn/ethereum-compatibility/evm-tracing.md"
          - Precompiled Contracts:
              - Overview: "learn/ethereum-compatibility/precompiles/overview.md"
              - Ethereum Precompiles: "learn/ethereum-compatibility/precompiles/ethereum.md"
              - Staking Precompile: "learn/ethereum-compatibility/precompiles/staking.md"
              - Deposit Precompile: "learn/ethereum-compatibility/precompiles/deposit.md"
              - KTON Precompile: "learn/ethereum-compatibility/precompiles/commitment-token.md"
              - USDT Precompile: "learn/ethereum-compatibility/precompiles/usdt.md"
              - State Storage Precompile: "learn/ethereum-compatibility/precompiles/state-storage.md"
              - Dispatch Precompile: "learn/ethereum-compatibility/precompiles/dispatch.md"
              - Conviction Voting Precompile: "learn/ethereum-compatibility/precompiles/conviction-voting.md"
      - Darwinia Staking:
          - Commitment Token: "learn/stake/commitment-token.md"
          - Staking Pallet: "learn/stake/staking.md"
          - Deposit Pallet: "learn/stake/deposit.md"
      - FAQs: "learn/faq.md"
  - Build In Darwinia:
      - Getting Started:
          - Token Transfer: "build/getting-started/transfer-token.md"
          - Staking: "build/getting-started/staking.md"
          - Governance: "build/getting-started/governance.md"
          - USDT Operations: "build/getting-started/usdt.md"
          - Multisig Wallet: "build/getting-started/multisig-wallet.md"
          - Creating a DAO: "build/getting-started/create-dao.md"
          - Darwinia 1.0 Migration:
            - Migrate Generate Account: "build/getting-started/migration/generate-account.md"
            - Migrate Multisig Account: "build/getting-started/migration/multisig-account.md"
      - Build In Darwinia:
          - Smart Contracts:
            - Interacting with Web3.js: "build/smart-contract/interact-with-web3js.md"
            - Interacting with Ethers.js: "build/smart-contract/interact-with-ethersjs.md"
            - Using Hardhat: "build/smart-contract/interact-with-hardhat.md"
            - Using Foundry: "build/smart-contract/interact-with-foundry.md"
            - Verifying Smart Contracts: "build/smart-contract/verify-contract.md"
          - Indexing Services:
              - Using SubQuery: "build/indexer/subquery.md"
      - Node Operator:
          - Database Snapshot: "build/chain/snapshot.md"
          - Running a Collator Node: "build/chain/run-collator-node.md"
          - Running an Archive Node: "build/chain/run-archive-node.md"
          - Running an EVM Tracing Node: "build/chain/run-evm-tracing-node.md"
          - Running a Development Node: "build/chain/run-dev-node.md"
  - RingDAO: "ring-dao.md"
  - Ecosystem Collaboration: "ecosystem.md"
