site_name: Darwinia Docs
site_url: https://docs.darwinia.network/
copyright: Copyright &copy; Darwinia Network
repo_url: https://github.com/darwinia-network/docs
repo_name: darwinia-network/docs
edit_uri: https://github.com/darwinia-network/docs/edit/main/docs
theme:
  name: material
  logo: resource/pics/darwinia-logo.png
  favicon: resource/pics/background.png
  font:
    text: San Francisco
    code: SFMono-Regular
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  generator: false
  homepage: https://darwinia.network
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darwinia-network
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/DarwiniaNetwork
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jbRk7znn4Q
    - icon: fontawesome/brands/telegram
      link: https://t.me/DarwiniaNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/darwinianetwork
  analytics:
    provider: google
    property: G-K2MGZ3GPEE

extra_css:
  - resource/stylesheets/extra.css

extra_javascript:
  - resource/script/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true
  - redirects:
      redirect_maps:
        "learn/chains/overview.md": "build/getting-started/networks/overview.md"
        "learn/chains/darwinia.md": "build/getting-started/networks/darwinia.md"
        "learn/chains/crab.md": "build/getting-started/networks/crab.md"
        "learn/chains/pangolin.md": "build/getting-started/networks/pangolin.md"
        "learn/chains/rollup.md": "build/getting-started/networks/rollup.md"
        "learn/wallets.md": "build/getting-started/wallets.md"
        "learn/ethereum-compatibility/precompiles/overview.md": "build/precompiles/overview.md"
        "learn/ethereum-compatibility/precompiles/ethereum.md": "build/precompiles/ethereum.md"
        "learn/ethereum-compatibility/precompiles/staking.md": "build/precompiles/staking.md"
        "learn/ethereum-compatibility/precompiles/deposit.md": "build/precompiles/deposit.md"
        "learn/ethereum-compatibility/precompiles/commitment-token.md": "build/precompiles/commitment-token.md"
        "learn/ethereum-compatibility/precompiles/usdt.md": "build/precompiles/usdt.md"
        "learn/ethereum-compatibility/precompiles/state-storage.md": "build/precompiles/state-storage.md"
        "learn/ethereum-compatibility/precompiles/dispatch.md": "build/precompiles/dispatch.md"
        "learn/ethereum-compatibility/precompiles/conviction-voting.md": "build/precompiles/conviction-voting.md"
        "build/chain/snapshot.md": "node-operators/snapshot.md"
        "build/chain/run-collator-node.md": "node-operators/run-collator-node.md"
        "build/chain/run-archive-node.md": "node-operators/run-archive-node.md"
        "build/chain/run-evm-tracing-node.md": "node-operators/run-evm-tracing-node.md"
        "build/chain/run-dev-node.md": "node-operators/run-dev-node.md"
        "build/getting-started/transfer-token.md": "community/guide/transfer-token.md"
        "build/getting-started/staking.md": "community/guide/staking.md"
        "build/getting-started/governance.md": "community/guide/governance.md"
        "build/getting-started/assethub-bridge.md": "community/guide/assethub-bridge.md"
        "build/getting-started/multisig-wallet.md": "community/guide/multisig-wallet.md"
        "build/getting-started/create-dao.md": "community/guide/create-dao.md"
        "build/getting-started/migration/generate-account.md": "community/guide/migration/generate-account.md"
        "build/getting-started/migration/multisig-account.md": "community/guide/migration/multisig-account.md"
        "build/smart-contract/interact-with-web3js.md": "build/ethereum-tools/interact-with-web3js.md"
        "build/smart-contract/interact-with-ethersjs.md": "build/ethereum-tools/interact-with-ethersjs.md"
        "build/smart-contract/interact-with-hardhat.md": "build/ethereum-tools/interact-with-hardhat.md"
        "build/smart-contract/interact-with-foundry.md": "build/ethereum-tools/interact-with-foundry.md"
        "build/smart-contract/verify-contract.md": "build/ethereum-tools/verify-contract.md"
        "community/ringdao.md": "community/orgs/ringdao.md"
        "community/dcdao.md": "community/orgs/dcdao.md"
        "community/ktondao.md": "community/orgs/ktondao.md"


nav:
  - Home: "index.md"
  - Learn:
      - Ethereum Compatibility:
          - Account System: "learn/ethereum-compatibility/account-system.md"
          - JSON-RPC APIs: "learn/ethereum-compatibility/jsonrpc.md"
          - Gas: "learn/ethereum-compatibility/gas.md"
          - EVM Tracing: "learn/ethereum-compatibility/evm-tracing.md"
      - Governance: "learn/governance.md"
      - Collator Staking: "learn/collator-staking.md"
      - FAQs: "learn/faq.md"
  - Developers:
      - Getting Started:
          - Networks:
            - Overview: "build/getting-started/networks/overview.md"
            - Darwinia: "build/getting-started/networks/darwinia.md"
            - Crab: "build/getting-started/networks/crab.md"
            - Pangolin: "build/getting-started/networks/pangolin.md"
            - Rollup: "build/getting-started/networks/rollup.md"
          - Wallets: "build/getting-started/wallets.md"
      - Development Tools:
          - Ethereum Tools:
            - Interacting with Web3.js: "build/ethereum-tools/interact-with-web3js.md"
            - Interacting with Ethers.js: "build/ethereum-tools/interact-with-ethersjs.md"
            - Using Hardhat: "build/ethereum-tools/interact-with-hardhat.md"
            - Using Foundry: "build/ethereum-tools/interact-with-foundry.md"
            - Verifying Smart Contracts: "build/ethereum-tools/verify-contract.md"
          - Indexing Services:
              - Using SubQuery: "build/indexer/subquery.md"
      - Precompiled Contracts:
            - Overview: "build/precompiles/overview.md"
            - Asset:
              - KTON: "build/precompiles/commitment-token.md"
              - USDT: "build/precompiles/usdt.md"
            - Staking:
              - Staking: "build/precompiles/staking.md"
              - Deposit: "build/precompiles/deposit.md"
            - Governance:
              - Conviction Voting: "build/precompiles/conviction-voting.md"
            - Utility:
              - Ethereum Mainnet: "build/precompiles/ethereum.md"
              - State Storage: "build/precompiles/state-storage.md"
              - Dispatch: "build/precompiles/dispatch.md"
  - Network Operators:
      - Database Snapshot: "node-operators/snapshot.md"
      - Running a Collator Node: "node-operators/run-collator-node.md"
      - Running an Archive Node: "node-operators/run-archive-node.md"
      - Running an EVM Tracing Node: "node-operators/run-evm-tracing-node.md"
      - Running a Development Node: "node-operators/run-dev-node.md"
  - Community:
      - Overview: "community/overview.md"
      - Community Organizations:
        - RingDAO: "community/orgs/ringdao.md"
        - DCDAO: "community//orgs/dcdao.md"
        - KtonDAO: "community//orgs/ktondao.md"
      - Community Guide:
          - How to Stake: "community/guide/staking.md"
          - Accounts:
            - How to Create a Multisig: "community/guide/multisig-wallet.md"
            - Darwinia 1.0 Migration:
              - Migrate Generate Account: "community/guide/migration/generate-account.md"
              - Migrate Multisig Account: "community/guide/migration/multisig-account.md"
          - Token Transfer:
            - Transfer Native Token: "community/guide/transfer-token.md"
            - Transfer AssetHub Token: "community/guide/assethub-bridge.md"
          - Governance: 
            - How to submit a Proposal: "community/guide/governance.md"
            - Creating a DAO: "community/guide/create-dao.md"