site_name: Darwinia Document
copyright: Copyright &copy; 2018 - 2024 Darwinia Network
repo_url: https://github.com/darwinia-network/document
repo_name: darwinia-network/document
edit_uri: https://github.com/darwinia-network/document/edit/main/docs
theme:
  name: material
  logo: resource/pics/darwinia-logo.png
  favicon: resource/pics/background.png
  font:
      text: Open Sans
      code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom

extra:
  generator: false
  homepage: https://darwinia.network
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darwinia-network
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/DarwiniaNetwork
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jbRk7znn4Q
    - icon: fontawesome/brands/telegram
      link: https://t.me/DarwiniaNetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/darwinianetwork

extra_css:
  - resource/stylesheets/extra.css

extra_javascript:
  - resource/script/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - def_list
  - attr_list
  - md_in_html
  - admonition

plugins:
  - search
  - git-revision-date-localized:
      type: date

nav:
  - Home: 'index.md'
  - Msgport:
    - Overview: 'msgport/overview.md'
    - Glossary: 'msgport/glossary.md'
    - Msgport Interfaces: 'msgport/interfaces.md'
    - Msgport Workflow: 'msgport/workflow.md'
    - Msgport API: 'msgport/api.md'
    - Msgport Scan: 'msgport/scan.md'
    - Messaging Protocols:
        - ORMP: 'msgport/messaging-protocols/ormp.md'
        - XCMP: 'msgport/messaging-protocols/xcmp.md'
        - LCMP: 'msgport/messaging-protocols/lcmp.md'
    - Supported Network: 'msgport/networks.md'
    - User Cases:
        - Token/Asset Bridge: 'msgport/user-cases/token-bridge.md'
        - Cross Chain Abstract Account: 'msgport/user-cases/abstract-account.md'
        - Multi Chains DAO Governance: 'msgport/user-cases/multichain-dao-governance.md'
    - Tutorial:
        - Pangolin > Sepolia Remix Demo: 'msgport/tutorial/remix-demo.md'
        - Pangolin > Sepolia Script Demo: 'msgport/tutorial/script-demo.md'
    - FAQ: 'msgport/faq.md'
    - TroubleSome: 'msgport/troublesome.md'
  - EVM+: 
    - Overview: 'evm/overview.md'
    - Chains And Explorers:
          - Overview: 'evm/chains/overview.md'
          - Darwinia Chain: 'evm/chains/darwinia.md'
          - Crab Chain: 'evm/chains/crab.md'
          - Pangolin Chain: 'evm/chains/pangolin.md'
          - Rollup Testnet: 'evm/chains/rollup.md'
    - Available Wallets: 'evm/wallets.md'
    - Ethereum Compatibility:
          - Account System: 'evm/ethereum-compatibility/account-system.md'
          - JSON-RPC API: 'evm/ethereum-compatibility/jsonrpc.md'
          - Gas Compatibility: 'evm/ethereum-compatibility/gas.md'
          - EVM Tracing: 'evm/ethereum-compatibility/evm-tracing.md'
          - Precompiled Contracts:
              - Overview: 'evm/ethereum-compatibility/precompiles/overview.md'
              - Ethereum: 'evm/ethereum-compatibility/precompiles/ethereum.md'
              - Staking: 'evm/ethereum-compatibility/precompiles/staking.md'
              - Deposit: 'evm/ethereum-compatibility/precompiles/deposit.md'
              - Commitment Token: 'evm/ethereum-compatibility/precompiles/commitment-token.md'
              - USDT: 'evm/ethereum-compatibility/precompiles/usdt.md'
              - StateStorage: 'evm/ethereum-compatibility/precompiles/state-storage.md'
              - Dispatch: 'evm/ethereum-compatibility/precompiles/dispatch.md'
              - Conviction Voting: 'evm/ethereum-compatibility/precompiles/conviction-voting.md'
    - Darwinia Staking:
          - Commitment Token: 'evm/darwinia-staking/commitment-token.md'
          - Staking Module: 'evm/darwinia-staking/staking.md'
          - Deposit Module: 'evm/darwinia-staking/deposit.md'
    - Governance: 'evm/governance.md'
    - Tutorial:
          - Transfer Token Guide: 'evm/tutorial/transfer-token.md'
          - Staking Guide: 'evm/tutorial/staking.md'
          - USDT Guide: 'evm/tutorial/usdt.md'
          - Multisig Wallet: 'evm/tutorial/multisig-wallet.md'
          - Create DAO Guide: 'evm/tutorial/create-dao.md'
          - Smart Contract Guide:
              - Interact With Web3.js: 'evm/tutorial/smart-contract/interact-with-web3js.md'
              - Interact With Ethers.js: 'evm/tutorial/smart-contract/interact-with-ethersjs.md'
              - Interact With Hardhat: 'evm/tutorial/smart-contract/interact-with-hardhat.md'
              - Interact With Foundry: 'evm/tutorial/smart-contract/interact-with-foundry.md'
              - Verify Smart Contract: 'evm/tutorial/smart-contract/verify-contract.md'
              - Awesome Tutorial: 'evm/tutorial/smart-contract/awesome-tutorial.md'
          - Chain Guide:
              - Chain Database Snapshot: 'evm/tutorial/chain/snapshot.md'
              - Run Collator Node: 'evm/tutorial/chain/run-collator-node.md'
              - Run Archive Node: 'evm/tutorial/chain/run-archive-node.md'
              - Run EVM Tracing Node: 'evm/tutorial/chain/run-evm-tracing-node.md'
              - Run Dev Node: 'evm/tutorial/chain/run-dev-node.md'
              - Run Relay Chain Testnet: 'evm/tutorial/chain/run-relay-chain-testnet.md'
          - Darwinia 1.0 Migration:
              - Migrate Generate Account: 'evm/tutorial/migration/generate-account.md'
              - Migrate Multisig Account: 'evm/tutorial/migration/multisig-account.md'
          - Indexer Guide:
              - SubQuery: 'evm/tutorial/indexer/subquery.md'
    - Glossary: 'evm/glossary.md'
    - FAQ: 'evm/faq.md'
  - RING: 'ring.md'
  - Ecosystem And Developer Incentive Program: 'ecosystem.md'
